language: ruby
rvm:
- jruby-19mode
- jruby-head
jdk:
- oraclejdk7
- oraclejdk8
- openjdk7
services:
- rabbitmq
env:
  matrix:
  - secure: AY3DsrPdsC8EQxGIGUHlvXeJNoPbsxESP7EXaDGTEFc8dHrWhdafOHwXFfERLFg8eAub1/qu01tjdcJcGf1OhdN3gM0Aic+EERknI/HD/6ZZifDKC6GDRv6F1uoKMzQmjuaZBzOjiaFTV3bZcp2pM3f7dO3LEfdKwXcZMRQ++YWYL+ntZbUPzvZ8K6/UGP3lvFF5jRpv2kDryFJa4pauZ6CnAdYFEnJB/8cB9IXJ5H+YzM7wGNl6gMJ7RPtdBV1BoeHkhBVHf2BEoHKAZXfL0FlCAGemQfAUH9eR+pdMD1RXoFZrbiQqiNIJdjufwMdyIRHIA7xc17QwR0uqjd/YJwh5g/n1sSFcC8DrKTlR+iZiPtbgF4ZITTaGteSTkRKu9v9UooMVUOsAmSbWlvXXXdTzSlo1KA3pgfnSxGy3M4osOTxO6TwL8+XJE4bmjgEgFJnUgHcGCargv9FIfZfIn8OVYiMnHd3Ab7hjej8aiPVByM9mf58UnfOd4GEmhG1VX6U3A+k57qWpm4DpxrRX1fpwek1ZNfEmuaWlBiuIxrkz5BloFUMGwGZPOI+GzJsR+zAEYhpJxAyNkB/s7PtQkl5VsIpP4UA1G5k/Qz4Aonw1fekzoIJgF1oiRqkegIwZG8luMq10uJXGLwUIlSuvKhzgyHd1IPlP6wt6HU3r+Nc=
  - secure: kiCxWTgtZJhJAOh1UQUu8RLfsZZg2ZyAq37kY+rNz3xzoRS7rO7naLm+wJzBPRoqUkK3CK1YR32CkzmwI8Mt1kl0OyiweK+9DAT+TlcyK58FB8cDmbfp6+LohyoQQFB/8NrbunbXp2aO/rkUh48YjT0E3qkHmcp26jmgwqDDWdxBWCL68YUHK2NFgSEpCGVWNAQslmj/2SL0uHw7gd74mtjd92OcS1n8VrkrwNLhmLa+QjUsP6sjkxOMjkQSF9qneMfW1s1pQeDXQF55TJr9f5uVEl4B0uRj7R06+EHPgSNY1ip6zB39Abmp7i04OP5Mgmm2UxRLZlSR5mqLY7eSsDIhzIrbcN9uDpypU+mMd9fyk4b5Wdk6jw3fByUHyNs4PpiA9Ckr/BNhJsBSKJ2LJyPhknrJITiCabmBAebVYdySGGahbTYKgCxww94Uk3nJKtVAoVhGacR/wFKrg2Qiq8h20Bjsb83SeSmkU0cvIDBFoOi/9A689bO75x5oseSoMyHjjahXLQk9DeUGdbEQnYNyHey3mX6bK3VS7ia4WUDxM7AGMYSINQZCVkTxln9noBToOpPagHwdt1KZznoVKGXxClhWlklNvKUvpWp9ZUFgncWnBc82A1kFEH6mQ4Z4IetKHDIz5ds1YzIXVFDzh/1P3omdDVSmgHJX8bgCKWg=
